Repository JuliaRegistries/RegistryCI.jl, pull requests merged in 2019-10, with the labels that each got.

#14 Update package description in README
  README.md
Labels: documentation

#20 Fix two very stupid typos that I made
  src/AutoMerge/github.jl
Labels: bug

#30 Fix a mistake I made in the "patch release does not narrow Julia compat"
  src/AutoMerge/semver.jl
Labels: bug

#43 Fix a typo in the `pr_has_no_blocking_comments` function
  src/AutoMerge/cron.jl
Labels: bug

#56 Update README.md
  README.md
Labels: documentation

#58 Add Acknowledgements section
  README.md
Labels: documentation

#62 Update description README
  README.md
Labels: documentation

#63 Update package description
  README.md
Labels: documentation

#64 Update description
  README.md
Labels: documentation

#66 Add the first set of integration tests
  .travis.yml
  src/AutoMerge/AutoMerge.jl
  src/AutoMerge/api_rate_limiting.jl
  src/AutoMerge/github.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/public.jl
  src/AutoMerge/pull-requests.jl
  src/AutoMerge/util.jl
  test/automerge-integration-utils.jl
  test/automerge-integration.jl
  test/automerge-unit.jl
  test/registryci.jl
  test/runtests.jl
  test/templates/feature_1/R/Requires/Compat.toml
  test/templates/feature_1/R/Requires/Deps.toml
  test/templates/feature_1/R/Requires/Package.toml
  test/templates/feature_1/R/Requires/Versions.toml
  test/templates/feature_1/Registry.toml
  test/templates/feature_2/R/Requires/Compat.toml
  test/templates/feature_2/R/Requires/Deps.toml
  test/templates/feature_2/R/Requires/Package.toml
  test/templates/feature_2/R/Requires/Versions.toml
  test/templates/feature_2/Registry.toml
  test/templates/master_1/Registry.toml
  test/templates/master_2/R/Requires/Compat.toml
  test/templates/master_2/R/Requires/Deps.toml
  test/templates/master_2/R/Requires/Package.toml
  test/templates/master_2/R/Requires/Versions.toml
  test/templates/master_2/Registry.toml
Labels: enhancement

#71 Remove Coveralls badge from README
  README.md
Labels: documentation

#80 Enable running from GitHub Actions.
  src/AutoMerge/AutoMerge.jl
  src/AutoMerge/ciservice.jl
  src/AutoMerge/cron.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/public.jl
  src/AutoMerge/pull-requests.jl
  src/AutoMerge/util.jl
  test/automerge-integration.jl
  test/automerge-unit.jl
Labels: enhancement
