Repository JuliaRegistries/RegistryCI.jl, pull requests merged in 2019-12, with the labels that each got.

#121 Run all package-loads under xvfb
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: breaking change, enhancement

#127 Create bors.toml
  Project.toml
  bors.toml
Labels: enhancement

#134 Better warning when a patch changes Julia compat
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: documentation

#138 Better warning when a patch changes Julia compat
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: documentation

#139 Set R_HOME to "*"
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: bugfix

#143 Suggest CompatHelper if package does not meet compat rules
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: enhancement

#145 Always check all guidelines
  src/AutoMerge/jll.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
Labels: breaking change, enhancement

#148 If a non-JLL package has a JLL package as a dependency, we will not require you to have a compat entry for the JLL package
  src/AutoMerge/guidelines.jl
  src/AutoMerge/jll.jl
Labels: breaking change, enhancement

#150 Reorganize the comment
  Project.toml
  src/AutoMerge/guidelines.jl
  src/AutoMerge/util.jl
Labels: enhancement

#152 Use the `automerge/decision` status to decide whether or not to merge
  src/AutoMerge/cron.jl
  test/automerge-integration.jl
Labels: breaking change, enhancement

#153 Enable automerging for JLL packages
  Project.toml
  src/AutoMerge/jll.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
Labels: breaking change, enhancement

#157 README: For now, compat entries are not required for JLL dependencies
  README.md
Labels: documentation

#159 Require at least Julia 1.3
  Project.toml
  test/automerge-integration-utils.jl
  test/automerge-integration.jl
  test/automerge-unit.jl
  test/registryci_registry_testing.jl
  test/runtests.jl
Labels: breaking change

#161 Fix a bug relating to some of the assertions
  Project.toml
  src/AutoMerge/cron.jl
Labels: bugfix

#162 Fix some more bugs, add some more tests, change the types of some thrown exceptions
  Project.toml
  src/AutoMerge/cron.jl
  src/AutoMerge/guidelines.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/types.jl
  test/automerge-integration.jl
  test/templates/feature_3/R/Req/Compat.toml
  test/templates/feature_3/R/Req/Deps.toml
  test/templates/feature_3/R/Req/Package.toml
  test/templates/feature_3/R/Req/Versions.toml
  test/templates/feature_3/Registry.toml
  test/templates/feature_4/R/Requires/Compat.toml
  test/templates/feature_4/R/Requires/Deps.toml
  test/templates/feature_4/R/Requires/Package.toml
  test/templates/feature_4/R/Requires/Versions.toml
  test/templates/feature_4/Registry.toml
Labels: breaking change, bugfix

#167 Staging for pull request #166
  LICENSE.md
  Project.toml
  src/AutoMerge/guidelines.jl
  src/AutoMerge/semver.jl
  test/automerge-unit.jl
Labels: bugfix

#169 For new version PRs, check that the version doesn’t already exist
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: enhancement

#170 Fix several JLL-related bugs
  Project.toml
  src/AutoMerge/guidelines.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
Labels: bugfix

#171 Use different waiting periods for JLL vs non-JLL packages
  Project.toml
  src/AutoMerge/AutoMerge.jl
  src/AutoMerge/automerge_comment.jl
  src/AutoMerge/cron.jl
  src/AutoMerge/jll.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/public.jl
  test/automerge-integration.jl
Labels: breaking change, enhancement

#182 When computing length of package name, exclude `_jll`
  Project.toml
  src/AutoMerge/guidelines.jl
  src/AutoMerge/new-package.jl
Labels: bugfix

#183 Add some more documentation
  .travis.yml
  INTEGRATION_TESTS.md
  Project.toml
  README.md
  bin/remember_to_update_registryci.jl
  bin/travis_cron.sh
  example_github_workflow_files/automerge.yml
  example_github_workflow_files/remember_to_update_registryci.yml
Labels: documentation
