Repository JuliaRegistries/RegistryCI.jl, pull requests merged in 2020-04, with the labels that each got.

#225 AutoMerge cron job should not exit with error if Travis CI failed on a pull request
  Project.toml
  src/AutoMerge/cron.jl
Labels: bug, bugfix, enhancement

#226 Added note on mandatory waiting period length
  Project.toml
  src/AutoMerge/util.jl
Labels: needs version bump

#231 Delete bors.toml
  bors.toml
Labels: needs version bump

#236 Install the Bors app on this repository
  bors.toml
Labels: needs version bump

#237 Update Travis configuration
  .travis.yml
Labels: needs version bump

#239 Better JLL enforcement
  .travis.yml
  Project.toml
  bors.toml
  example_github_workflow_files/automerge.yml
  src/AutoMerge/cron.jl
  src/AutoMerge/guidelines.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/public.jl
  src/AutoMerge/pull-requests.jl
  src/registry_testing.jl
  test/automerge-integration.jl
Labels: breaking change, enhancement

#240 Allow new packages to have initial version number of the form `X.0.0`
  Project.toml
  src/AutoMerge/guidelines.jl
  test/automerge-unit.jl
Labels: enhancement

#242 Fix a bug
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: bugfix

#243 Disable the "URL ends in /name.jl.git" check
  Project.toml
  src/AutoMerge/new-package.jl
Labels: enhancement
