Repository JuliaRegistries/RegistryCI.jl, pull requests merged in 2021-03, with the labels that each got.

#353 If the package is in a subdirectory, check that the repo URL ends in `/PackageName.jl.git`
  Project.toml
  src/AutoMerge/guidelines.jl
  src/AutoMerge/new-package.jl
Labels: bug fix

#356 If the "Pkg.add" check failed, the "OSI license" check should fail gracefully (instead of crashing AutoMerge)
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: bug fix

#358 More fixes for the `pkgdir_from_depot` and `meets_version_has_osi_license` functions
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: bug fix

#364 AutoMerge should not crash if the registry consistency tests fail
  Project.toml
  src/AutoMerge/guidelines.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/public.jl
Labels: bug fix

#367 Fix the `load_registry_dep_uuids` function
  Project.toml
  src/registry_testing.jl
  test/registryci_registry_testing.jl
Labels: bug fix

#366 fix indentation in pkg name similarity list
  Project.toml
  src/AutoMerge/guidelines.jl
Labels: automerge comment formatting, bug fix

#370 Don't run VersionVigilante on pull requests
  .github/workflows/VersionVigilante_pull_request.yml
  Project.toml
Labels: continuous integration (ci)

#369 Run the "name similarity" check last
  Project.toml
  src/AutoMerge/new-package.jl
Labels: automerge comment formatting

#373 Automatically pass VersionVigilante on the trying branch
  .github/workflows/VersionVigilante_bors.yml
  Project.toml
Labels: continuous integration (ci)
