Repository JuliaRegistries/RegistryCI.jl, pull requests merged in 2021-05, with the labels that each got.

#393 Add some checks to make sure that the regex docs never get out of sync
  docs/src/regexes.md
Labels: documentation

#398 README: Put the CI badges in a table
  README.md
Labels: documentation

#399 Fix the commit regex to account for carriage returns
  Project.toml
  src/AutoMerge/pull-requests.jl
Labels: bug fix

#404 README: remove the Bors badge, and put all other badges into the table
  README.md
Labels: documentation

#405 Auto-generate the documentation page with the list of AutoMerge guidelines
  Project.toml
  docs/make.jl
  docs/src/guidelines.md
  src/AutoMerge/AutoMerge.jl
  src/AutoMerge/assert.jl
  src/AutoMerge/changed_files.jl
  src/AutoMerge/dependency_confusion.jl
  src/AutoMerge/guidelines.jl
  src/AutoMerge/jll.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/types.jl
  src/AutoMerge/update_status.jl
Labels: documentation

#406 If AutoMerge checks fail, in the comment, link to both the General registry README and the (autogenerated) AutoMerge guideline docs in the RegistryCI.jl docs
  Project.toml
  src/AutoMerge/util.jl
Labels: automerge comment

#408 Set `JULIA_PKG_PRECOMPILE_AUTO` env variable
  src/AutoMerge/guidelines.jl
Labels: bug fix

#410 Use the correct relative path for the package as specified in the `Registry.toml` file
  Project.toml
  src/AutoMerge/AutoMerge.jl
  src/AutoMerge/changed_files.jl
  src/AutoMerge/guidelines.jl
  src/AutoMerge/jll.jl
  src/AutoMerge/not_automerge_applicable.jl
  src/AutoMerge/package_path_in_registry.jl
  src/AutoMerge/pull_requests.jl
  src/AutoMerge/semver.jl
  test/automerge-unit.jl
Labels: bug fix

#409 A few tweaks to the docs for AutoMerge guidelines
  Project.toml
  docs/src/guidelines.md
  src/AutoMerge/guidelines.jl
Labels: documentation
