Repository JuliaRegistries/RegistryCI.jl, pull requests merged in 2021-01, with the labels that each got.

#320 Migrate from Travis to GitHub Actions
  .github/workflows/CompatHelper.yml
  .github/workflows/TagBot.yml
  .github/workflows/ci_integration.yml
  .github/workflows/ci_unit.yml
  .gitignore
  .travis.yml
  INTEGRATION_TESTS.md
  LICENSE.md
  Project.toml
  README.md
  bors.toml
  teamcity_settings.kts
  test/Project.toml
  test/automerge-integration-utils.jl
  test/automerge-integration.jl
  test/runtests.jl
Labels: continuous integration (ci)

#325 Fix CI
  .github/workflows/ci_integration.yml
  test/automerge-integration.jl
Labels: continuous integration (ci)

#327 Fix CI (again)
  .github/workflows/ci_integration.yml
  Project.toml
  bors.toml
  test/automerge-integration.jl
Labels: continuous integration (ci)

#328 Only run the integration tests on the `staging` and `trying` branches
  .github/workflows/ci_integration.yml
  README.md
  test/automerge-integration.jl
Labels: continuous integration (ci)

#321 Put the TagBot "fixup PR" inside a try-catch block
  Project.toml
  src/TagBot/fixup.jl
Labels: TagBot, bug fix

#324 AutoMerge: If the PR is not from `JuliaRegistrator` or `jlbuild`, exit with success
  Project.toml
  src/AutoMerge/AutoMerge.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/not-automerge-applicable.jl
  src/AutoMerge/public.jl
  src/AutoMerge/pull-requests.jl
Labels: breaking change

#329 Fix a bug
  Project.toml
  src/AutoMerge/not-automerge-applicable.jl
  test/automerge-integration.jl
Labels: bug fix

#332 Fix some bugs in control flow
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/not-automerge-applicable.jl
  src/AutoMerge/public.jl
  src/AutoMerge/pull-requests.jl
Labels: bug fix

#334 Fix a bug in the "author not authorized to AutoMerge" code path
  Project.toml
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/pull-requests.jl
Labels: bug fix

#318 Restructure guideline verification
  src/AutoMerge/automerge_comment.jl
  src/AutoMerge/changed_files.jl
  src/AutoMerge/guidelines.jl
  src/AutoMerge/jll.jl
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
  src/AutoMerge/pull-requests.jl
  src/AutoMerge/types.jl
Labels: enhancement

#339 Fix the registry consistency tests on Julia nightly
  src/AutoMerge/semver.jl
  src/registry_testing.jl
Labels: bug fix

#341 Nicer collection and processing of guidelines.
  src/AutoMerge/new-package.jl
  src/AutoMerge/new-version.jl
Labels: bug fix, enhancement
