Repository JuliaRegistries/RegistryCI.jl, pull requests merged in 2024-01, with the labels that each got.

#536 AutoMerge: Respect the `Override AutoMerge: name similarity is okay` label
  docs/src/guidelines.md
  example_github_workflow_files/automerge.yml
  src/AutoMerge/guidelines.jl
  src/AutoMerge/pull_requests.jl
  test/automerge-unit.jl
Labels: feature

#540 AutoMerge: temporarily disable the "Require `[compat]` for stdlib dependencies" feature"
  src/AutoMerge/guidelines.jl
  src/AutoMerge/util.jl
Labels: feature

#539 AutoMerge: Allow skipping sequential versions with author-approval criteria
  docs/src/guidelines.md
  docs/src/private-registries.md
  example_github_workflow_files/automerge.yml
  src/AutoMerge/cron.jl
  src/AutoMerge/guidelines.jl
  src/AutoMerge/pull_requests.jl
  src/AutoMerge/util.jl
  test/automerge-unit.jl
Labels: feature

#521 Upgrade to Documenter v1
  docs/Project.toml
  docs/make.jl
Labels: continuous integration (ci)

#545 Change "CI logs" to "AutoMerge" logs
  src/AutoMerge/guidelines.jl
Labels: automerge comment
